### ISSUE TITLE
resultprocess.py Doesn't create default output directory './creds/' before it tries to use it.

### ISSUE THREAD

**Issue by BirdHacks** [skelsec/pypykatz_server#1]
If you don't give the server an output directory, it seems to use .\creds\, but it never creates this directory and doesn't catch the error from trying to access a directory that doesn't exist.

When not specifying an output file with -o:
```
PS C:\Users\<username>\Desktop\pypykatz_server-master> python server.py socket -l 192.168.1.3 -p 80
[+] Starting server...
[+] Waiting for clients...
[+] Client connected from 192.168.1.3:6271
[+] Handling client...
DEBUG:pypykatz:===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====
DEBUG:pypykatz:CPU arch: X64
DEBUG:pypykatz:OS: None
DEBUG:pypykatz:BuildNumber: 17134
DEBUG:pypykatz:MajorVersion: 6
DEBUG:pypykatz:MSV timestamp: 1552431330
DEBUG:pypykatz:===== BASIC INFO END =====
DEBUG:pypykatz:None
[+] Client finished!
Got data!
Traceback (most recent call last):
  File "C:\Users\<username>\Desktop\pypykatz_server-master\pypykatz_server\resultprocess.py", line 27, in process_result
    with open(outfile, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'creds\\192_168_1_3_6271_<random>.json'
```

Specifying a directory that the current shell permissions can get to:
```
PS> python server.py socket -l 192.168.1.3 -p 80 -o C:\Users\<username>\Desktop\
[+] Starting server...
[+] Waiting for clients...
[+] Client connected from 192.168.1.3:6266
[+] Handling client...
DEBUG:pypykatz:===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====
DEBUG:pypykatz:CPU arch: X64
DEBUG:pypykatz:OS: None
DEBUG:pypykatz:BuildNumber: 17134
DEBUG:pypykatz:MajorVersion: 6
DEBUG:pypykatz:MSV timestamp: 1552431330
DEBUG:pypykatz:===== BASIC INFO END =====
DEBUG:pypykatz:None
[+] Client finished!
Got data!
```

It also doesn't check for permissions access to a provided directory before trying to actually access it.
```
PS C:\Users\<username>\Desktop\pypykatz_server-master> python server.py socket -l 192.168.1.3 -p 80 -o C:\
[+] Starting server...
[+] Waiting for clients...
[+] Client connected from 192.168.1.3:6284
[+] Handling client...
DEBUG:pypykatz:===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====
DEBUG:pypykatz:CPU arch: X64
DEBUG:pypykatz:OS: None
DEBUG:pypykatz:BuildNumber: 17134
DEBUG:pypykatz:MajorVersion: 6
DEBUG:pypykatz:MSV timestamp: 1552431330
DEBUG:pypykatz:===== BASIC INFO END =====
DEBUG:pypykatz:None
[+] Client finished!
Got data!
Traceback (most recent call last):
  File "C:\Users\<username>\Desktop\pypykatz_server-master\pypykatz_server\resultprocess.py", line 27, in process_result
    with open(outfile, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\192_168_1_3_6284_fc723233.json'
```

**Comment by BirdHacks** [comment]
Fixed in pull request #2
